### ISSUE TITLE
TV channels not connecting

### ISSUE THREAD

**Issue by Grandma-Betty** [rbuehlma/pvr.teleboy#37] opened 2019-12-17 11:43 UTC
Since a few days TV channels are showing what they are currently sending out but they do not connect when trying to access them.
Using it on LibreELEC 9.2 with Teleboy free which worked fine before and without changing anything on the setup it's not working anymore.

**Comment by rbuehlma** [comment] 2019-12-17 11:45
Are you locate in Switzerland? If not, you will probably get blocked by Teleboy. If yes, please provide a complete debug log.

**Comment by Grandma-Betty** [comment] 2019-12-17 12:10
Yes I am from switzerland. Here are the logs.
Edit: As you can see inside the logs I am using two different PVR clients. One for Teleboy which is not working and the other one is working fine, just to let you know it is not a network issue.

**Comment by rbuehlma** [comment] 2019-12-17 12:14
You are using quite an old version of the addon:
pvr.teleboy v18.0.25.1 installed

Can you do an upgrade to v18.1.6 and retry?

**Comment by Grandma-Betty** [comment] 2019-12-17 13:20
How can I upgrade when the current repo inside the LibreELEC GUI is showing only the old version of Teleboy?
Tried to download the **pvr.teleboy-18.1.6-Leia.zip** from github, copy it manually to the filesystem and then tried to install it by using the **install from .ZIP-file** option inside the LibreELEC GUI. But it's not installing.
I already uninstalled the old version of Teleboy and installing from untrusted sources are enabled.
Thanks for helping me out.

**Comment by rbuehlma** [comment] 2019-12-17 13:34
Just downloading the source from github does not work for PVR addons since they need to be build for each environment. I do not know how the addon update process of LE is. You might want to ask this in the LE forum. If you get some information, it would be great if you can post the link here.

**Comment by tuxfuxch** [comment] 2019-12-17 19:14
i had the same problem and the new version solved it (ubuntu; installed over package manager)
BTW great addon. THX a lot.

**Comment by leoleo18** [comment] 2019-12-18 09:21
Hi there,
I can relate to that that issue as well. I am using raspberry pi3 with buster, kodi 18.4 and teleboy 18.0.25. I also tried what Fabian tried and of course didnt work. The problem is that I dont know how to get the newest version of teleboy if that not included in the apt sources... ...

**Comment by leoleo18** [comment] 2019-12-18 16:20
@tuxfuxch could you please point where I can find the compiled latest version for ubuntu that you used?

**Comment by rbuehlma** [comment] 2019-12-18 16:37
For Ubuntu it is quite simple:
Add this PPA to your Ubuntu and from there you always get the current stable Kodi and addons:
https://launchpad.net/~team-xbmc/+archive/ubuntu/ppa

**Comment by leoleo18** [comment] 2019-12-18 16:59
(sorry for the level of noobness...)
I tried  but I get the error:
 aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Raspbian/buster

I thought that raspbian compatible/similar with Ubuntu. no?
`nevertheless, i tried to download the i386 deb file from launchpad and install it manually with dpgk  but the architecture is wrong (i386 vs armhf).

Unfortnuately, currently i think there no other version than 18.0.25 available on any raspbian version. And this old version is not functional any more.

**Comment by rbuehlma** [comment] 2019-12-18 17:04
No, sorry, I do not think that raspbian and Ubuntu are compatible. As already mentioned, to get an updated version for LE, you should ask in their forum on how to achieve that.

**Comment by Alcantor** [comment] 2019-12-18 21:51
Hello. I've have a similar Problem since Yesterday. I've updated to 18.1.6 but the problem persist. Two/Three days ago it was working very well. Has the teleboy API change? I'am using ubuntu 19.04 and the pacage manager.

By the way: The problem affect also watchteleboy.
See issue https://github.com/reduzent/watchteleboy/issues/29

> After a quick look into the issue, it appears that teleboy.ch switched from the Apple HLS protocol to the MPEG-DASH.

**Comment by rbuehlma** [comment] 2019-12-18 21:53
Please provide a complete debug log

**Comment by Alcantor** [comment] 2019-12-18 22:03
Is that helping you?

[kodi.log](https://github.com/rbuehlma/pvr.teleboy/files/3980740/kodi.log)

```
2019-12-18 23:01:41.174 T:139871834330880   ERROR: Open - error probing input format, https://zh2-2-dash-live.zahs.tv/HD_tsr1/manifest.mpd?z32=MF2WI2LPL5RW6ZDFMNZT2YLBMMTGG43JMQ6TCNKFGE4TMMZVG5CDQOKDIVCUMLJUGQ2TSOCDHFATORJYGAZEERBSEZWWC6DSMF2GKPJVGAYDAJTNNFXHEYLUMU6TEMJQEZYHEZLGMVZHEZLEL5WGC3THOVQWOZJ5MZZCM43JM46WMNLDGBRTMMDGMJSTEN3DHBTDKZBRGRTGGMRZGJQWEYRXMQYTQMJGOVZWK4S7NFSD25DFNRSWE33ZL43DOMZYG44TIMJZ
2019-12-18 23:01:41.174 T:139871834330880   ERROR: OpenDemuxStream - Error creating demuxer
```

**Comment by rbuehlma** [comment] 2019-12-18 22:07
Could you check whether the addon inputstream.adaptive is active? It should be automatically when pvr.zattoo is installed but it does not seem to be the case for you.

**Comment by Alcantor** [comment] 2019-12-18 22:17
You're the best. inputstream.adaptive was disabled, I've activated it and it work again. Thanks you. Could be yet this addon mandatory since the switch to MPEG-DASH?

**Comment by rbuehlma** [comment] 2019-12-18 22:18
Yes, dash does only work with inputstream.adaptive but Kodi should automatically activate it as soon as pvr.teleboy is installed. Not sure why this did not happen.

**Comment by rbuehlma** [comment] 2019-12-19 07:41
Seems to be resolved by activating inputstream.adaptive

**Closed as completed by rbuehlma** 2019-12-19 07:41 UTC

**Comment by Grandma-Betty** [comment] 2019-12-30 09:00
Still having the same issue on LibreELEC 9.2 with Teleboy PVR 18.1.8.1.

**Comment by rbuehlma** [comment] 2019-12-30 09:03
Please provide a new complete debug log.

**Comment by Grandma-Betty** [comment] 2019-12-30 09:07
There you are.
Thank you in advance.

**Comment by rbuehlma** [comment] 2019-12-30 09:11
Its not a debug log (debug level is missing) but it looks like inputstream.adaptive is not active. It should work if you activate the inputstream.adaptive addon.

**Comment by Grandma-Betty** [comment] 2019-12-30 09:28
Oops, sorry about that.
Here's the Debug Log again.

inputstream.adaptive should be activated as the GUI is showing that it is running. Can I double check this, maybe by SSH?

**Comment by rbuehlma** [comment] 2019-12-30 09:35
You can try to de- and re-activate it. If that does not help, there might be an issue with the version of LE.

**Comment by Grandma-Betty** [comment] 2019-12-30 09:38
omg, that did the trick.
Silly that a simply restart did not work but manually disabling and enabling was the solution.
Thanks a lot dude!

**Comment by Grandma-Betty** [comment] 2019-12-30 10:17
Just one more thing: I noticed i have to do this steps everytime I reboot LibreELEC.
Can you imagine why this is happening and how I can resolve this issue?

**Comment by rbuehlma** [comment] 2019-12-30 10:18
Sorry no. You probably want to report this against LE.

**Comment by Grandma-Betty** [comment] 2019-12-30 10:19
OK I will and post the solution here when there is one available.

**Comment by Grandma-Betty** [comment] 2019-12-31 10:58
Finally got the workaround solution and posted it [here](https://forum.libreelec.tv/thread/21069-inputstream-adaptive-not-starting-correctly/#post132314).
