### ISSUE TITLE
PVR client crashes Kodi on Android os

### ISSUE THREAD

**Issue by Hir0-84** [rbuehlma/pvr.teleboy#4] opened 2017-10-14 09:06 UTC
Hi guys,

I found your pvr client on kodinerds forum but since I do not speak german I'm reporting the bug here. First of all you did a great job with both zattoo and teleboy client, it is exactly what I was looking for a year now.

I have tested the addon using kodi nightly 20171013 and 20171012 on Nougat both arm64-v8a (smartphone) and v7a (android tv). In both case kodi crashes as soon as it starts and I had to clean the app data to be able to use kodi again. The last message in log file before it crashes is:

> Curl::Debug - TEXT: Curl_http_done: called premature == 0
> Curl::Debug - TEXT: Connection #1 host t.teleboy.ch left intact

On linux it does not work neither but it does not crash. Below please find the log when I try to play any channel from teleboy. With zattoo pvr the streaming works on both android and linux only if I use hls instead of dash.

> ERROR: CCurlFile::FillBuffer - Failed: URL using bad/illegal format or missing URL(3)
> 10:52:39.383 T:140400442459904   ERROR: CCurlFile::Open failed with code 0 for http://tv.api.teleboy.ch/users/TYPE html>
>                                             <html>
>                                             <head><script type="text/javascript">window.NREUM|(NREUM=%7b%7d%2fbroadcasts%3fbegin%3d2017-10-13%2008%3a52%3a36&acceptencoding=gzip&customrequest=GET&end=2017-10-17%2008%3a52%3a36&expand=logos&limit=500&skip=0&sort=station&station=384&x-teleboy-apikey=69d4547562510efe1b5d354bc34656fb34366b6c1023739ce46958007bf17ee9&x-teleboy-device-type=desktop&x-teleboy-session=qqhhq5p1524tonmrvf6jukb9j0&x-teleboy-version=1.5
> 10:52:39.383 T:140400442459904   ERROR: AddOnLog: Teleboy PVR Client: Error getting epg for channel 384.
> 10:52:39.415 T:140400937400064   ERROR: CCurlFile::FillBuffer - Failed: URL using bad/illegal format or missing URL(3)
> 10:52:39.415 T:140400937400064   ERROR: CCurlFile::Open failed with code 0 for http://tv.api.teleboy.ch/users/TYPE html>
>                                             <html>
>                                             <head><script type="text/javascript">window.NREUM|(NREUM=%7b%7d%2fbroadcasts%3fbegin%3d2017-10-13%2008%3a52%3a36&acceptencoding=gzip&customrequest=GET&end=2017-10-17%2008%3a52%3a36&expand=logos&limit=500&skip=0&sort=station&station=385&x-teleboy-apikey=69d4547562510efe1b5d354bc34656fb34366b6c1023739ce46958007bf17ee9&x-teleboy-device-type=desktop&x-teleboy-session=qqhhq5p1524tonmrvf6jukb9j0&x-teleboy-version=1.5
> 10:52:39.415 T:140400937400064   ERROR: AddOnLog: Teleboy PVR Client: Error getting epg for channel 385.
> 10:55:56.807 T:140403345379904   ERROR: CCurlFile::FillBuffer - Failed: URL using bad/illegal format or missing URL(3)
> 10:55:56.807 T:140403345379904   ERROR: CCurlFile::Open failed with code 0 for http://tv.api.teleboy.ch/users/TYPE html>
>                                             <html>
>                                             <head><script type="text/javascript">window.NREUM|(NREUM=%7b%7d%2fstream%2flive%2f5%3falternative%3dfalse&acceptencoding=gzip&customrequest=GET&x-teleboy-apikey=69d4547562510efe1b5d354bc34656fb34366b6c1023739ce46958007bf17ee9&x-teleboy-device-type=desktop&x-teleboy-session=qqhhq5p1524tonmrvf6jukb9j0&x-teleboy-version=1.5
> 10:55:56.807 T:140403345379904   ERROR: AddOnLog: Teleboy PVR Client: Error getting live stream url for channel 5.
> 10:55:56.816 T:140403345379904  NOTICE: VideoPlayer::OpenFile: pvr://channels/tv/Tutti i Canali/pvr.teleboy_5.pvr
> 10:55:56.905 T:140401876924160  NOTICE: Creating InputStream
> 10:55:56.906 T:140401876924160   ERROR: CVideoPlayer::OpenInputStream - error opening [pvr://channels/tv/Tutti i Canali/pvr.teleboy_5.pvr]
> 10:55:56.906 T:140401876924160  NOTICE: CVideoPlayer::OnExit()

Regads,

**Comment by rbuehlma** [comment] 2017-10-19 20:20
Sorry for the late response. Seems I have to watch my own repo to receive notifications about new issues.

About your cases:

Could you provide the version of the pvr and inputstream.adaptive addon you are using for both, android and linux?

It seems that others have similar issues with the addon on Android (FireTV). Unfortunately, I can not reproduce these issues. Could you try to fetch the crash log from the android devices including stacktrace.

Your issue on Linux seems to be a different one. I tried to reproduce that one but was not able to. Could you provide a full debug log there?

**Comment by rbuehlma** [comment] 2017-10-19 21:32
I probably have found the crash issue. You get somehow redirected to t.teleboy.ch. Maybe because of Android. With version 18.0.9, you can now select to use t.teleboy.ch in the settings. This hopefully solves your issue. The version should be in the upcoming nightlies.

**Comment by Hir0-84** [comment] 2017-10-19 22:01
Hi Rbuehlma thanks for replying!

On linux I have solved, I just cleaned the .kodi folder and updated the pvr client to version 18.0.8. The problematic one was 18.0.5. Tomorrow I will test the new nightly on Android. Thanks! 

PS: will be possible to encrypt the password store in settings.xml file on both zattoo and teleboy pvr?

**Comment by rbuehlma** [comment] 2017-10-19 22:05
The addon requires the password in plaintext during login. Therefore, any encryption would only be security through obscurity.

**Comment by Hir0-84** [comment] 2017-10-20 06:13
I have tested the version 18.0.9, it does not crash anymore but if I do not activate t.teleboy.ch I get the following error message in the log file. The good thing is if I switch t.teleboy.ch on (the old url) with the same credentials it works and it does not crash the app, so maybe you have handled some exception. 

> 07:59:21.846 T:508475470928  NOTICE: AddOnLog: Teleboy PVR Client: Got cookie: colang=it.
> 07:59:22.138 T:508475470928   ERROR: AddOnLog: Teleboy PVR Client: No user settings found.
> 07:59:22.138 T:508475470928   ERROR: AddOnLog: Teleboy PVR Client: Login failed
> 07:59:22.139 T:508475470928  NOTICE: PVR Manager: Starting
> 07:59:22.408 T:507970057296   ERROR: CCurlFile::Open failed with code 404 for http://tv.api.teleboy.ch/users//recordings/planned?desc=1&expand=flags,logos&limit=100&skip=0&sort=date|acceptencoding=gzip&customrequest=GET&x-teleboy-apikey=69d4547562510efe1b5d354bc34656fb34366b6c1023739ce46958007bf17ee9&x-teleboy-device-type=desktop&x-teleboy-session=h0ltapb8oltqfalhlh5cmo6cga&x-teleboy-version=1.5
> 07:59:22.408 T:507970057296   ERROR: AddOnLog: Teleboy PVR Client: Error getting recordings of type planned.
> 07:59:22.494 T:507970057296   ERROR: CCurlFile::Open failed with code 404 for http://tv.api.teleboy.ch/users//recordings/ready?desc=1&expand=flags,logos&limit=100&skip=0&sort=date|acceptencoding=gzip&customrequest=GET&x-teleboy-apikey=69d4547562510efe1b5d354bc34656fb34366b6c1023739ce46958007bf17ee9&x-teleboy-device-type=desktop&x-teleboy-session=h0ltapb8oltqfalhlh5cmo6cga&x-teleboy-version=1.5
> 07:59:22.495 T:507970057296   ERROR: AddOnLog: Teleboy PVR Client: Error getting recordings of type ready.
> 07:59:22.495 T:507970057296  NOTICE: PVR Manager: Started
> 07:59:22.515 T:508475470928  NOTICE: Start - EPG thread started
> 07:59:23.519 T:507965912144 WARNING: EPG - UpdateFromScraper - channel not found, can't update
> 
> > 07:59:21.846 T:508475470928  NOTICE: AddOnLog: Teleboy PVR Client: Got cookie: colang=it.
> 07:59:22.138 T:508475470928   ERROR: AddOnLog: Teleboy PVR Client: No user settings found.
> 07:59:22.138 T:508475470928   ERROR: AddOnLog: Teleboy PVR Client: Login failed
> 07:59:22.139 T:508475470928  NOTICE: PVR Manager: Starting
> 07:59:22.408 T:507970057296   ERROR: CCurlFile::Open failed with code 404 for http://tv.api.teleboy.ch/users//recordings/planned?desc=1&expand=flags,logos&limit=100&skip=0&sort=date|acceptencoding=gzip&customrequest=GET&x-teleboy-apikey=69d4547562510efe1b5d354bc34656fb34366b6c1023739ce46958007bf17ee9&x-teleboy-device-type=desktop&x-teleboy-session=h0ltapb8oltqfalhlh5cmo6cga&x-teleboy-version=1.5
> 07:59:22.408 T:507970057296   ERROR: AddOnLog: Teleboy PVR Client: Error getting recordings of type planned.
> 07:59:22.494 T:507970057296   ERROR: CCurlFile::Open failed with code 404 for http://tv.api.teleboy.ch/users//recordings/ready?desc=1&expand=flags,logos&limit=100&skip=0&sort=date|acceptencoding=gzip&customrequest=GET&x-teleboy-apikey=69d4547562510efe1b5d354bc34656fb34366b6c1023739ce46958007bf17ee9&x-teleboy-device-type=desktop&x-teleboy-session=h0ltapb8oltqfalhlh5cmo6cga&x-teleboy-version=1.5
> 07:59:22.495 T:507970057296   ERROR: AddOnLog: Teleboy PVR Client: Error getting recordings of type ready.
> 07:59:22.495 T:507970057296  NOTICE: PVR Manager: Started
> 07:59:22.515 T:508475470928  NOTICE: Start - EPG thread started
> 07:59:23.519 T:507965912144 WARNING: EPG - UpdateFromScraper - channel not found, can't update

**Comment by rbuehlma** [comment] 2017-10-20 07:01
Yes, this is what I expected. Android devices seem to get redirected to t.teleboy.ch. I assume this is some testing environment. The addon does not handle this redirect. By fixing it to t.teleboy.ch, this is solved. Now the question is, if it is possible to detect this switch automatically.

If I try to implement this switch, are you able to build and test the addon for Android?

**Comment by Hir0-84** [comment] 2017-10-20 21:07
I may try to compile and test it on Android or I might simply wait and test the nightlies when they are released. By the way your fix works on the Android TV as well.

**Comment by rbuehlma** [comment] 2017-10-22 12:18
I have implemented an automated switch to t.teleboy.ch.
It should now work without manually switching.

Closing this issue.

**Closed by rbuehlma** 2017-10-22 12:18 UTC
